package secretname

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"testing"
)

var updateHashes = flag.Bool("update-hashes", false, "rewrite hashes_gen.go from the lists in testdata/names.txt")

func sortedDigests(k kind, names []string) []string {
	out := make([]string, 0, len(names))
	for _, n := range names {
		d := digest(k, n)
		out = append(out, string(d[:]))
	}
	sort.Strings(out)
	return out
}

func lengths(names []string) []int {
	seen := map[int]bool{}
	var out []int
	for _, n := range names {
		if !seen[len(n)] {
			seen[len(n)] = true
			out = append(out, len(n))
		}
	}
	sort.Ints(out)
	return out
}

func genTable(b *bytes.Buffer, name string, k kind, names []string) {
	fmt.Fprintf(b, "const %s = \"\" +\n", name)
	for _, d := range sortedDigests(k, names) {
		b.WriteString("\t\"")
		for i := 0; i < len(d); i++ {
			fmt.Fprintf(b, "\\x%02x", d[i])
		}
		b.WriteString("\" +\n")
	}
	b.WriteString("\t\"\"\n\n")
}

func generated(l nameLists) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate (see hashed.go); DO NOT EDIT.\n\npackage secretname\n\n")
	genTable(&b, "tabFile", kindFile, l.files)
	genTable(&b, "tabFolder", kindFolder, l.folders)
	genTable(&b, "tabPair", kindPair, l.pairs)
	genTable(&b, "tabSuffix", kindSuffix, l.suffixes)
	genTable(&b, "tabPrefixAny", kindPrefixAny, l.prefixAny)
	genTable(&b, "tabPrefixPrivate", kindPrefixPrivate, l.prefixPrivate)
	fmt.Fprintf(&b, "var lensSuffix = %#v\n", lengths(l.suffixes))
	fmt.Fprintf(&b, "var lensPrefixAny = %#v\n", lengths(l.prefixAny))
	fmt.Fprintf(&b, "var lensPrefixPrivate = %#v\n", lengths(l.prefixPrivate))
	out, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	return out
}

// Threat: a name added to the readable list but not to the hash table (or the
// other way round), so the shipped check and the list people read part ways.
func TestHashTablesAreCurrent(t *testing.T) {
	want := generated(lists(t))
	if *updateHashes {
		if err := os.WriteFile("hashes_gen.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile("hashes_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(bytes.ReplaceAll(got, []byte("\r\n"), []byte("\n")), want) {
		t.Fatal("hashes_gen.go does not match testdata/names.txt: run go generate in internal/secretname")
	}
}

// Every listed name is found by the lookup it is listed for, and the lists
// have no duplicates and no name that is not already folded.
func TestEveryListedNameIsFound(t *testing.T) {
	l := lists(t)
	check := func(k kind, names []string) {
		seen := map[string]bool{}
		for _, n := range names {
			if seen[n] {
				t.Errorf("%q listed twice", n)
			}
			seen[n] = true
			if fold(n) != n {
				t.Errorf("%q is not lower-case", n)
			}
			if !has(k, n) {
				t.Errorf("%q (%c) is in the list but not the table", n, k)
			}
		}
	}
	check(kindFile, l.files)
	check(kindFolder, l.folders)
	check(kindPair, l.pairs)
	for _, n := range l.suffixes {
		if !hasSuffixIn("x" + n) {
			t.Errorf("suffix %q not found", n)
		}
	}
	for _, n := range l.prefixAny {
		if !hasPrefixIn(kindPrefixAny, n+"x") {
			t.Errorf("prefix %q not found", n)
		}
	}
	for _, n := range l.prefixPrivate {
		if !hasPrefixIn(kindPrefixPrivate, n+"x") {
			t.Errorf("prefix %q not found", n)
		}
	}
}
